name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run bot    
        run: 
          node index.js
        env:
          GITHUB_ACTIONS: true
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
      - name: Build and Push
        run: |
          # 1. Construimos para la arquitectura que AWS App Runner necesita (amd64)
          docker build --platform linux/amd64 -t willytpfw/ollama-telegram-bot
          
          # 2. Subimos la imagen ya autenticados
          docker push willytpfw/ollama-telegram-bot
