name: Git Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: Run bot
        run: node index.js
        env:
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
  Hook: 
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Llamar WebHook
          if: ${{ success() }}
          run: |
            curl -X POST https://hooks.nabu.casa/gAAAAABqh76ggj_JMSO9ERNexwb0sr5iBtQlhE3-1GOCAr71nTMHTajDYLjc9yYHdDnBpP-00LEcCiKLaaUGwbPDYU-vEefE4NG7XNp4Pk4GzPCr2P6fJ_TW4L6ehL9k8bo9EgPln-0fW8OpjMvNsUtkXU7hEAXsQFbcdRktFIKnp1zKOMyeXLY= \
                 -H "Content-Type: application/json" \
